jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Fetch Server Data
        run: bash scripts/fetch-dev-data.sh

      - name: build
        run: npm run build